In [2]:
import numpy as np

In [3]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
my_array, type(my_list), type(my_array)

(array([1, 2, 3, 4, 5]), list, numpy.ndarray)

In [4]:
import numpy as np

zeros_array = np.zeros((2, 3))    # 2x3 array of zeros
ones_array = np.ones((3, 3))      # 3x3 array of ones
full_array = np.full((2, 2), 7)    # 2x2 array filled with 7
range_array = np.arange(0, 10, 2)  # array with values from 0 to 8 with a step of 2
linspace_array = np.linspace(0, 1, 5)  # array with 5 evenly spaced values between 0 and 1

print("Array of zeros:\n", zeros_array)
print("Array of ones:\n", ones_array)
print("Array of sevens:\n", full_array)
print("Array of range:\n", range_array)
print("Array of linspace:\n", linspace_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array of sevens:
 [[7 7]
 [7 7]]
Array of range:
 [0 2 4 6 8]
Array of linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [4]:
import numpy as np

random_array = np.random.rand(2, 3)  # 2x3 array with random values between 0 and 1
random_array

array([[0.0917527 , 0.75775934, 0.24480997],
       [0.13719064, 0.22190558, 0.54812603]])

In [5]:
my_array.dtype

dtype('int64')