# 👾 The Alien Invasion!

**Scenario:**

You're a data analyst at the Earth Defence Organisation (EDO). You've just received a transmission containing **data about an alien fleet** heading towards Earth! The transmission contains vital data about each alien spaceship's **dimensions, speed, and weapon power**. Your job is to analyze this data to provide the EDO with the insights needed to prepare Earth's defenses. 

**Exercise:**

The transmission is an matrix (an array) which contains data for each spaceship. Every line represents one spaceship, with values in the order of: **length** (in meters), **width** (in meters), **height** (in meters), **speed** (in km/s), and **weapon power** (on a scale of 1-10).

In [31]:
import numpy as np


fleet_data = np.array([
    [120, 40, 25, 2.5, 10],
    [85, 60, 30, 5.0, 5],
    [100, 50, 35, 4.5, 7],
    [120, 40, 25, 2.5, 9],
    [150, 50, 30, 3.0, 10],
], dtype=np.float32)

**Your tasks:**

1. Calculate and print the total number of spaceships.

In [32]:
fleet_lenght = fleet_data.shape[0]
f"Number of ships in the fleet: {fleet_lenght}"

'Number of ships in the fleet: 5'

2. Calculate and print the average spaceship size (volume). 

In [33]:
ships_lenghts = fleet_data[:, 0]
ships_widths = fleet_data [:, 1]
ships_heights = fleet_data [:, 2]

print(f"Lengths: {ships_lenghts}")
print(f"Widhts: {ships_widths}")
print(f"Hights: {ships_heights}")

Lengths: [120.  85. 100. 120. 150.]
Widhts: [40. 60. 50. 40. 50.]
Hights: [25. 30. 35. 25. 30.]


In [34]:
ships_volumes = ships_lenghts*ships_widths*ships_heights
ships_volumes

array([120000., 153000., 175000., 120000., 225000.], dtype=float32)

In [35]:
Ships_mean_volume = ships_volumes.mean()
f"Mean volume of the ships: {Ships_mean_volume} m3"

'Mean volume of the ships: 158600.0 m3'

3. Identify and print the speed of the fastest spaceship.

In [40]:
ships_speeds = fleet_data[:,3]
max_speed= ships_speeds.max()
ship_max_speed = np.argmax(ships_speeds)
f"The fastest spaceship {ship_max_speed} travles at {max_speed} km/s"

'The fastest spaceship 1 travles at 5.0 km/s'

4. Determine and print the number of spaceships with the maximum weapon power.

In [54]:
ships_power = fleet_data[:,-1]
ships_with_max_power_mask = ships_power == 10 
n_ships_max_power = ships_with_max_power_mask.sum()

f"The number of ships with maximum power equals {n_ships_max_power}"


'The number of ships with maximum power equals 2'

In [49]:
ships_power.max()

10.0

In [50]:
np.array ([1,2,3]).sum()

6

In [51]:
np.array ([True, False, False, False,  True]).sum()

2

5. Find and print the mean speed of spaceships with the maximum weapon power.

In [56]:
ships_speeds , ships_with_max_power_mask

(array([2.5, 5. , 4.5, 2.5, 3. ], dtype=float32),
 array([ True, False, False, False,  True]))

In [58]:
ships_speeds[ships_with_max_power_mask].mean()

2.75

Remember, the fate of Earth depends on your quick and accurate analysis. Good luck! 🍀